stages:
  - build
  - deploy

build:
  image: node:latest   
  stage: build
  script:
    - yarn install     
    - CI=false && GENERATE_SOURCEMAP=false && yarn build
  artifacts:
    paths:
      - build/        
pages:
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none   
  script:
    # Rename the CRA `build` folder to `public`
    - mv build public         
  artifacts:
    paths:
      -  feature/pipeline
