stages:
  - build
  - deploy

build:
  image: node:latest   
  stage: build
  script:
    - yarn install     
    - CI=false && GENERATE_SOURCEMAP=false && yarn build
  artifacts:
    paths:
      - build/        
pages:
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none   
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
      - pulbic
