stages:
  - build

build:
  image: node:latest    
  stage: build
  variables: 
    # Replace this with your site URL
    PUBLIC_URL: https://kdt-gitlab.elice.io/gada-client/  
  script:
    - yarn install      
    - yarn build
  artifacts:
    paths:
      - build/      
